#!/usr/bin/env python3
"""Regenerate the signed fixtures embedded in test/unit/calibration/test_qe_update.cpp.

The test binary cannot sign for itself: tweetnacl.h is PRIVATE to
nukex4_calibration, and exposing a signing entry point purely for tests would
put test-only code into the shipped library. So fixtures are signed here and
embedded as constants. Run this and paste the output when a fixture body
changes.

    python3 tools/gen_qe_update_fixtures.py
"""
import base64, hashlib, json

# Test-only key material. The secret half is published in the test file on
# purpose -- it protects nothing and makes the fixtures reproducible.
SEED = bytes.fromhex("860e72a0957e3b7bc130ce6d264e31a4f26c1e79aeb9013e7f6abf7c0aa8568f")
PUB  = bytes.fromhex("143211773272d53bdcefa5a1eae7d32e99833af0ac5da2729e9063b41e6d217d")

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
KEY = Ed25519PrivateKey.from_private_bytes(SEED)

DB_BODY = '{"schema_version":1,"cameras":{},"filters":{}}'
DB_SHA512 = hashlib.sha512(DB_BODY.encode()).hexdigest()

def manifest(db_version, schema_version, sha512, db_bytes=len(DB_BODY)):
    return (
        '{"schema_version":%d,"db_version":%d,"db_sha512":"%s","db_bytes":%d,'
        '"n_cameras":61,"n_sensors":26,"released_utc":"2026-09-10T00:00:00Z",'
        '"summary":"Adds 6 cameras."}' % (schema_version, db_version, sha512, db_bytes)
    )

def sig_b64(body: str) -> str:
    return base64.b64encode(KEY.sign(body.encode())).decode()

WRONG_SHA = "b" * 128

FIXTURES = {
    "kDbBody":            DB_BODY,
    "kDbSig":             sig_b64(DB_BODY),
    "kDbSha512":          DB_SHA512,
    "kManifestV14":       manifest(14, 1, DB_SHA512),
    "kManifestV14Sig":    sig_b64(manifest(14, 1, DB_SHA512)),
    "kManifestV14Bad":    manifest(14, 1, WRONG_SHA),
    "kManifestV14BadSig": sig_b64(manifest(14, 1, WRONG_SHA)),
    "kManifestV12":       manifest(12, 1, DB_SHA512),
    "kManifestV12Sig":    sig_b64(manifest(12, 1, DB_SHA512)),
    "kManifestV99Schema": manifest(14, 99, DB_SHA512),
    "kManifestV99SchemaSig": sig_b64(manifest(14, 99, DB_SHA512)),
    "kManifestForged":    manifest(99, 1, DB_SHA512),   # signed by NOBODY
    "kJunk":              "{not json",
    "kJunkSig":           sig_b64("{not json"),
    "kTestPubHex":        PUB.hex(),
}

print("// Generated by tools/gen_qe_update_fixtures.py -- do not hand-edit.")
for name, value in FIXTURES.items():
    escaped = value.replace('\\', '\\\\').replace('"', '\\"')
    print('static const char* %-22s = "%s";' % (name, escaped))
